on:
  push:
    branches:
      - release
name: "Build & Release"
jobs:
  check-bats-version:
    name: Build & Release APK
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: ‘zulu’
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle



